variable "aws_region" {}
variable "audit_bucket_name" {}
variable "audit_account_name" {}
variable "audit_account_no" {}
variable "infra_account_no" {}
variable "billing_account_no" {}
variable "auth_account_no" {}
variable "spoke1_account_no" {}
variable "customer_name" {}
variable "environment" {}
variable "owner_tag" {}
variable "aws_credentials_path" {}
#variable "cloudtrail_bucket" {}
