variable "azure_pipeline" {}
variable "vpc_id" {}
variable "instance_type" {}
variable "subnet_ids" {}
variable "corporate_ip" {}
variable "instance_key" {}
variable "devops_organisation" {}
variable "devops_pat" {}
variable "devops_pool_name" {}
variable "environment_tag" {}
variable "owner_tag" {}