variable "aws_region" {}
variable "identity_provider_name" {}
variable "azure_ssouser_policy" {}
variable "azure_ssouser" {}
variable "billing_assume_role_name" {}
variable "security_assume_role_name" {}
variable "infra_assume_role_name" {}
variable "spoke1_assume_role_name" {}
variable "billing_account_no" {}
variable "auth_account_no" {}
variable "audit_account_no" {}
variable "infra_account_no" {}
variable "spoke1_account_no" {}
variable "infra_role" {}
variable "spoke1_role" {}
variable "aws_credentials_path" {}
