variable "aws_region" {}
variable "aws_credentials_path" {}
variable "billing_bucket_name" {}
variable "billing_account_name" {}
variable "billing_account_no" {}
variable "customer_name" {}
variable "environment" {}
variable "owner_tag" {}
#variable "cloudtrail_bucket" {}
